#65 fix abandon function
UE4-OceanProject/OceanProject pull request #73
Opened 2018-03-24 14:15 UTC by TheBegining

use “Add Torque in Radians”instead“Add Torque” in BP_ManOfWar

2018-03-25 19:12 UTC, saschaelble commented
Thank you!

2018-05-09 18:13 UTC, dotcamdev approved these changes

2018-05-09 18:19 UTC, dotcamdev requested changes
This will need to be changed from 4.18 to Master.

I can do this on my end and then add it to my next commit. Thanks

2018-05-11 00:06 UTC, dotcamdev commented
This issue has been fixed in PR #79 that has been pushed to master just now.

2018-05-11 00:06 UTC, closed without merging